#!/bin/bash
# export GOOGLE_APPLICATION_CREDENTIALS=./serviceaccount.json

export VACANCIES_GCP_PROJECT=position-scanner
export VACANCIES_GCP_PROJECT_LOCATION=europe-west1
export VACANCIES_WEBHOOK=TODO
export VACANCIES_FIREBASE_PROJECT_ID=TODO
