#!/bin/bash
# export GOOGLE_APPLICATION_CREDENTIALS=./serviceaccount.json

export VACANCIES_GCP_PROJECT=position-scanner
export VACANCIES_GCP_PROJECT_LOCATION=europe-west1
export VACANCIES_WEBHOOK=TODO
export VACANCIES_FIREBASE_PROJECT_ID=TODO
# export VACANCIES_CALL_ROOM_ENDPOINT=https://$VACANCIES_GC_PROJECT_LOCATION-$VACANCIES_GC_PROJECT.cloudfunctions.net/CallRoom
# export VACANCIES_SCHEDULER_LOCATION=projects/$VACANCIES_GC_PROJECT/locations/$VACANCIES_GC_PROJECT_LOCATION
# export VACANCIES_SCHEDULER_TIMEZONE=Europe/Kyiv
# export VACANCIES_SCHEDULER_MAX_RETRY_COUNT=2
# export VACANCIES_SCHEDULER_RETRY_PERIOD=5m
